// Generated by etc/list_apps.py - do not edit by hand.
.pragma library

var apps = [
    {
        "id": "bssh",
        "name": "Avahi SSH Server Browser",
        "icon": "image://icon/network-wired",
        "exec": "/usr/bin/bssh"
    },
    {
        "id": "bvnc",
        "name": "Avahi VNC Server Browser",
        "icon": "image://icon/network-wired",
        "exec": "/usr/bin/bvnc"
    },
    {
        "id": "avahi-discover",
        "name": "Avahi Zeroconf Browser",
        "icon": "image://icon/network-wired",
        "exec": "/usr/bin/avahi-discover"
    },
    {
        "id": "brave-origin",
        "name": "Brave Origin",
        "icon": "image://icon/brave-origin",
        "exec": "brave-origin"
    },
    {
        "id": "btop",
        "name": "btop++",
        "icon": "image://icon/btop",
        "exec": "btop"
    },
    {
        "id": "org.chipass.ChiPass",
        "name": "ChiPass",
        "icon": "image://icon/org.chipass.ChiPass",
        "exec": "ChiPass"
    },
    {
        "id": "com.danklinux.dankcalendar",
        "name": "Dank Calendar",
        "icon": "image://icon/com.danklinux.dankcalendar",
        "exec": "dcal open"
    },
    {
        "id": "org.gnome.Papers",
        "name": "Document Viewer",
        "icon": "image://icon/org.gnome.Papers",
        "exec": "papers"
    },
    {
        "id": "emacs",
        "name": "Emacs",
        "icon": "image://icon/emacs",
        "exec": "emacs"
    },
    {
        "id": "emacsclient",
        "name": "Emacs (Client)",
        "icon": "image://icon/emacs",
        "exec": "sh -c \"if [ -n \\\\\"\\\\$*\\\\\" ]; then exec /usr/bin/emacsclient --alternate-editor= --display=\\\\\"\\\\$DISPLAY\\\\\" \\\\\"\\\\$@\\\\\"; else exec /usr/bin/emacsclient --alternate-editor= --create-frame; fi\" sh"
    },
    {
        "id": "enteauth",
        "name": "Ente Auth",
        "icon": "image://icon/enteauth",
        "exec": "enteauth"
    },
    {
        "id": "org.gnome.Nautilus",
        "name": "Files",
        "icon": "image://icon/org.gnome.Nautilus",
        "exec": "nautilus --new-window"
    },
    {
        "id": "org.flameshot.Flameshot",
        "name": "Flameshot",
        "icon": "image://icon/org.flameshot.Flameshot",
        "exec": "/usr/bin/flameshot"
    },
    {
        "id": "gammastep-indicator",
        "name": "Gammastep Indicator",
        "icon": "image://icon/gammastep",
        "exec": "gammastep-indicator"
    },
    {
        "id": "lstopo",
        "name": "Hardware Locality lstopo",
        "icon": "image://icon/hwloc",
        "exec": "lstopo"
    },
    {
        "id": "Helix",
        "name": "Helix",
        "icon": "image://icon/helix",
        "exec": "helix"
    },
    {
        "id": "kitty",
        "name": "kitty",
        "icon": "image://icon/kitty",
        "exec": "kitty"
    },
    {
        "id": "libreoffice-startcenter",
        "name": "LibreOffice",
        "icon": "image://icon/libreoffice-startcenter",
        "exec": "libreoffice"
    },
    {
        "id": "libreoffice-base",
        "name": "LibreOffice Base",
        "icon": "image://icon/libreoffice-base",
        "exec": "libreoffice --base"
    },
    {
        "id": "libreoffice-calc",
        "name": "LibreOffice Calc",
        "icon": "image://icon/libreoffice-calc",
        "exec": "libreoffice --calc"
    },
    {
        "id": "libreoffice-draw",
        "name": "LibreOffice Draw",
        "icon": "image://icon/libreoffice-draw",
        "exec": "libreoffice --draw"
    },
    {
        "id": "libreoffice-impress",
        "name": "LibreOffice Impress",
        "icon": "image://icon/libreoffice-impress",
        "exec": "libreoffice --impress"
    },
    {
        "id": "libreoffice-math",
        "name": "LibreOffice Math",
        "icon": "image://icon/libreoffice-math",
        "exec": "libreoffice --math"
    },
    {
        "id": "libreoffice-writer",
        "name": "LibreOffice Writer",
        "icon": "image://icon/libreoffice-writer",
        "exec": "libreoffice --writer"
    },
    {
        "id": "librewolf",
        "name": "LibreWolf",
        "icon": "image://icon/librewolf",
        "exec": "/usr/lib/librewolf/librewolf"
    },
    {
        "id": "localsend",
        "name": "LocalSend",
        "icon": "image://icon/localsend",
        "exec": "localsend"
    },
    {
        "id": "io.mgba.mGBA",
        "name": "mGBA",
        "icon": "image://icon/io.mgba.mGBA",
        "exec": "mgba-qt"
    },
    {
        "id": "nvim",
        "name": "Neovim",
        "icon": "image://icon/nvim",
        "exec": "nvim"
    },
    {
        "id": "qv4l2",
        "name": "Qt V4L2 test Utility",
        "icon": "image://icon/qv4l2",
        "exec": "qv4l2"
    },
    {
        "id": "qvidcap",
        "name": "Qt V4L2 video capture utility",
        "icon": "image://icon/qvidcap",
        "exec": "qvidcap"
    },
    {
        "id": "vim",
        "name": "Vim",
        "icon": "image://icon/gvim",
        "exec": "vim"
    },
    {
        "id": "vlc",
        "name": "VLC media player",
        "icon": "image://icon/vlc",
        "exec": "/usr/bin/vlc --started-from-file"
    },
    {
        "id": "yazi",
        "name": "Yazi File Manager",
        "icon": "image://icon/yazi",
        "exec": "yazi"
    }
];
